// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DevRelConForm","status":true,"description":"DevRelCon事前登録が終わった時に実行するプラグイン","parameters":{"applicationKey":"b27f90a0af9b304cd7376c903599065afddeeaf57ff716e977495358c36db92d","clientKey":"25d74196e6468eb36d190f95423f939ad12e59ea0ab7c8e9259477bdeefb64cd"}},
{"name":"111_InputForm","status":true,"description":"フォーム作って文字入力（修正版）","parameters":{}}
];
